defaults:
  - perceptual_encoder: lcrs_image_encoder
  - plan_proposal: lcrs_plan_proposal
  - plan_recognition: lcrs_plan_recognition
  - distribution:  lcrs_distribution
  - visual_goal: default
  - language_goal: lcrs_language_encoder
  - action_decoder: lcrs_action_decoder
  - optimizer: adam
  - lr_scheduler: constant
  - bc_z_lang_decoder: none
  - mia_lang_discriminator: none
  - proj_vis_lang: default
  - /annotations@val_instructions: new_playtable_validation

_target_: lcrs.models.lcrs.Lcrs
_recursive_: false

kl_beta: ${loss.kl_beta}
kl_balancing_mix: ${loss.kl_balancing_mix}
state_reconstruction_weight: ${loss.state_reconstruction_weight}
use_bc_z_auxiliary_loss: false
bc_z_auxiliary_loss_beta: ${loss.bc_z_auxiliary_loss_beta}
use_mia_auxiliary_loss: false
mia_auxiliary_loss_beta: ${loss.mia_auxiliary_loss_beta}
replan_freq: 30
use_clip_auxiliary_loss: true
clip_auxiliary_loss_beta: ${loss.clip_auxiliary_loss_beta}
