defaults:
  - perceptual_encoder: lcrs_image_encoder
  - plan_proposal: lcrs_plan_proposal
  - plan_recognition: lcrs_plan_recognition
  - distribution:  lcrs_distribution
  - language_goal: lcrs_language_encoder
  - visual_goal: lcrs_visual_encoder
  - action_decoder: lcrs_action_decoder
  - optimizer: adam
  - lr_scheduler: constant
  - /annotations@val_instructions: new_playtable_validation

_target_: lcrs.models.lcrs.Lcrs
_recursive_: false

state_reconstruction_weight: ${loss.state_reconstruction_weight}
language_weight: ${loss.language_weight}
plan_weight: ${loss.plan_weight}
action_gripper_weight: ${loss.action_gripper_weight}
action_joints_weight: ${loss.action_joints_weight}

replan_freq: 30
